Add EternalCombat to docs system, Add Contribute section to each project
EternalCodeTeam/Docs pull request #35
Opened 2023-06-14 17:55 UTC by CitralFlo

2023-06-16 09:23 UTC, Osnixer approved these changes
Dobra robota nie znalazłem tutej do zmiany ;)

2023-06-16 19:00 UTC, Rollczi requested changes
Nie da się zrobić jakiejś templatki na contribute np. w komponencie? bo dużo już tutaj copypaste a wystarczy pewnie to generować z 1 komponentu

2023-06-17 17:02 UTC, CitralFlo commented
> Nie da się zrobić jakiejś templatki na contribute np. w komponencie? bo dużo już tutaj copypaste a wystarczy pewnie to generować z 1 komponentu

Zerknij proszę do pliku Contribute.vue i powiedz czy jest możliwość dodania formatowania kodu tak jak w markdownie, aby od razu pojawial sie guzik copy. Stworzylem component i działa wszystko gucii

2023-06-19 10:36 UTC, vLuckyyy approved these changes

2023-06-19 10:36 UTC, vLuckyyy commented on docs/.vitepress/config.ts
> +                { text: 'ℹ️ Contribute', link: '/eternalcore/contribute'}
Ta emotka trochę według mnie nie pasuje.

2023-06-19 10:36 UTC, vLuckyyy commented on docs/components/Contribute.vue
> +    </div>
Nie wystarczy zrobić czegoś takiego -> `coś tam komand`, jak jest rozproszone na cały poziom konteneru na docsy to dość dziwnie to wygląda

2023-06-19 11:14 UTC, Rollczi commented on docs/.vitepress/config.ts
> +                { text: 'ℹ️ Contribute', link: '/eternalcore/contribute'}
🌈

2023-06-19 14:09 UTC, Rollczi approved these changes

2023-06-19 14:10 UTC, merged