Add GitCheck to Docs system - initial commit
EternalCodeTeam/Docs pull request #36
Opened 2023-06-18 12:06 UTC by CitralFlo

2023-06-18 12:21 UTC, Osnixer approved these changes
Wygląda dobrze, podstawowy kodzik jest mały opis do tego wszystkiego - Dobra robota!

2023-06-18 15:40 UTC, vLuckyyy requested changes

2023-06-18 15:40 UTC, vLuckyyy commented on docs/.vitepress/config.ts
> +                { text: '✨ Features', link: '/gitcheck/features' },
To daj jako usage

2023-06-18 15:40 UTC, vLuckyyy commented on docs/.vitepress/config.ts
> +                { text: '🔧 Installation', link: '/gitcheck/installation' },
Installation wrzuc do Getting Started, tyle wystarczy

2023-06-18 15:40 UTC, vLuckyyy commented on docs/gitcheck/introduction.md
> +# ChatFormatter wiki's
ChatFormatter?

2023-06-18 16:53 UTC, vLuckyyy requested changes

2023-06-18 16:53 UTC, vLuckyyy commented on docs/gitcheck/introduction.md
> +* [Features, Command and Usage](features.md)
Commands? GitCheck nie ma komend, to jest libka do javy

2023-06-19 10:23 UTC, Rollczi approved these changes

2023-06-19 10:32 UTC, vLuckyyy approved these changes

2023-06-19 10:53 UTC, merged